// <auto-generated />
using System;
using GestaoImoveisAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoImoveisAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250523190032_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestaoImoveisAPI.Models.Bills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("RentalContractId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ValidationDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RentalContractId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("GestaoImoveisAPI.Models.RentalContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndContract")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RenterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartContract")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RenterId");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("GestaoImoveisAPI.Models.Renter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Renter");
                });

            modelBuilder.Entity("GestaoImoveisAPI.Models.Bills", b =>
                {
                    b.HasOne("GestaoImoveisAPI.Models.RentalContract", "RentalContract")
                        .WithMany("Bills")
                        .HasForeignKey("RentalContractId");

                    b.OwnsOne("SharedClasses.ValueObjects.Money", "Value", b1 =>
                        {
                            b1.Property<int>("BillsId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(65,30)")
                                .HasColumnName("Value");

                            b1.HasKey("BillsId");

                            b1.ToTable("Bills");

                            b1.WithOwner()
                                .HasForeignKey("BillsId");
                        });

                    b.Navigation("RentalContract");

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("GestaoImoveisAPI.Models.RentalContract", b =>
                {
                    b.HasOne("GestaoImoveisAPI.Models.Renter", "Renter")
                        .WithMany("Contracts")
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SharedClasses.ValueObjects.Money", "RentalValue", b1 =>
                        {
                            b1.Property<int>("RentalContractId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(65,30)")
                                .HasColumnName("RentalValue");

                            b1.HasKey("RentalContractId");

                            b1.ToTable("Contract");

                            b1.WithOwner()
                                .HasForeignKey("RentalContractId");
                        });

                    b.OwnsOne("SharedClasses.ValueObjects.Adress", "Adress", b1 =>
                        {
                            b1.Property<int>("RentalContractId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("City");

                            b1.Property<string>("Complement")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("Complement");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("Neighborhood");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("Number");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("ZipCode");

                            b1.HasKey("RentalContractId");

                            b1.ToTable("Contract");

                            b1.WithOwner()
                                .HasForeignKey("RentalContractId");
                        });

                    b.Navigation("Adress")
                        .IsRequired();

                    b.Navigation("RentalValue")
                        .IsRequired();

                    b.Navigation("Renter");
                });

            modelBuilder.Entity("GestaoImoveisAPI.Models.Renter", b =>
                {
                    b.OwnsOne("SharedClasses.ValueObjects.CPF", "CPF", b1 =>
                        {
                            b1.Property<int>("RenterId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("CPF");

                            b1.HasKey("RenterId");

                            b1.ToTable("Renter");

                            b1.WithOwner()
                                .HasForeignKey("RenterId");
                        });

                    b.OwnsOne("SharedClasses.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<int>("RenterId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("RenterId");

                            b1.ToTable("Renter");

                            b1.WithOwner()
                                .HasForeignKey("RenterId");
                        });

                    b.Navigation("CPF")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("GestaoImoveisAPI.Models.RentalContract", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("GestaoImoveisAPI.Models.Renter", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
